baseURL = "http://example.org/"
languageCode = "pt-br"
paginate = 6
theme = "portio"
title = "APMCMS"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "Quem Somos"
url = "#about"
weight = 2
[[menu.main]]
name = "Parceiros"
url = "#service"
weight = 3
[[menu.main]]
name = "Work"
url = "#portfolio"
weight = 4
[[menu.main]]
name = "Resume"
url = "#resume"
weight = 5
[[menu.main]]
name = "Números"
url = "#skills"
weight = 6
[[menu.main]]
name = "Blog"
url = "#blog"
weight = 7
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 8

# Sitemap Menu
[[menu.sitemap]]
name = "Quem Somos"
url = "about"
weight = 1
[[menu.sitemap]]
name = "Contato"
url = "#"
weight = 2
[[menu.sitemap]]
name = "Politicas de Privacidade"
url = "#"
weight = 3
[[menu.sitemap]]
name = "Ultimas noticias"
url = "#"
weight = 4

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "Todos os direitos reservados copyright © APMCMS 2023"
footerLogo = "images/contact/logo_apm_footer_200.png"
# We're using formspree.io for form handling, paste your formspree url below
fabformURL  = "https://fabform.io/f/JpTXRUa"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"
access_token = "4f854ad7a2f9a5196eddbf58d121de37"

[params.address]
address = "Rua das Hortências, SN, Pituba, Salvador-BA CEP 41810-010"
email = "apmcms.ssa@gmail.com"
openingHours = "Seg à Qui 6:30 às 10:30 <br> Sex 6:30 às 12:30"
phone = "71 3358-3258 | 71 99667-4032"

[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/"
weight = 2
[[params.social]]
icon = "fa-pinterest-square"
url = "https://www.pinterest.com/"
weight = 3
[[params.social]]
icon = "fa-instagram"
url = "https://www.instagram.com/apmcms/"
weight = 4



